layout_spectrum: 0.37937664333730936
typography_spectrum: 0.09705372806638479
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.13517180853523314
  lightness: 0.07247491902671754
  saturation: 0.5629272130317986
  rhythmicContrast: 0.3230636832304299
content_rating:
  adult: false
opengraph:
  type: ''
  appId: ''
author:
  name: ''
  url: ''
  email: ''
name: SteveGW - Game Art
navigation:
  - name: Home
    url: 'http://stevegw.today'
    type: external
title: Game Art exploration
